title: Arun Brahma
logo: /assets/img/arun_brahma.png
description: Lead Machine Learning Engineer (LLMs (fine-tuning, alignment, quantization), RAG, Information Retrieval)
show_downloads: false
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-seo-tag
