name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write     # Gives write access to gh-pages branch
  pages: write       # Needed for GitHub Pages deployments
  id-token: write    # Needed for GitHub Pages deployments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          BASE_URL: 'https://arunbrahma.com'

      - name: Create CNAME file
        run: echo "arunbrahma.com" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: arunbrahma.com
          force_orphan: true
